kind: pipeline
type: kubernetes
name: default
steps:
  - name: build-arm64
    image: golang:1.20.2-alpine
    environment:
      GOOS: linux
      GOARCH: arm64
      outputpath: ./dist/$GOOS-$GOARCH
    commands:
      - apk add --no-cache git gcc musl-dev tar
      - mkdir -p $outputpath
      - go mod tidy
      - go build -v -o ./dist/arm64/BilibiliDanmuRobot -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r etc $outputpath
      - cp readme.md $outputpath
      - tar czvf ./dist/BilibiliDanmuRobot_Linux_arm64_v1.0.5.tar.gz $outputpath/*
      - ls -al dist
      - ls -al $outputpath
      - rm -rf $outputpath
      - cd dist
      - tar xvf BilibiliDanmuRobot_Linux_arm64_v1.0.5.tar.gz