kind: pipeline
type: kubernetes
name: default
steps:
  - name: prebuild
    image: golang:1.21.4-alpine
    volumes:
      - name: cache
        path: /gobuild
    environment:
      GOCACHE: /gobuild/gocache
      GOPATH: /gobuild/gopath
    commands:
      - go mod tidy
    when:
      event:
        - tag
  - name: build-linux-arm64
    image: golang:1.21.4-alpine
    volumes:
      - name: cache
        path: /gobuild
    environment:
      GOOS: linux
      GOARCH: arm64
      GOCACHE: /gobuild/gocache
      GOPATH: /gobuild/gopath
    commands:
      - export outputpath=./dist/$GOOS-$GOARCH
      - apk add --no-cache git gcc musl-dev tar
      - cd cli && mkdir -p $outputpath
#      - go mod tidy
      - go build -v -o $outputpath/BilibiliDanmuRobot -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r ../etc $outputpath
      - cp ../readme.md $outputpath
      - cd $outputpath
      - md5sum BilibiliDanmuRobot
      - tar czvf ../BilibiliDanmuRobot_Linux_arm64_${DRONE_TAG}.tar.gz ./*
      - cd ../../
      - rm -rf $outputpath
    when:
      event:
        - tag
    depends_on:
      - prebuild
  - name: build-linux-amd64
    image: golang:1.21.4-alpine
    volumes:
      - name: cache
        path: /gobuild
    environment:
      GOOS: linux
      GOARCH: amd64
      GOCACHE: /gobuild/gocache
      GOPATH: /gobuild/gopath
    commands:
      - export outputpath=./dist/$GOOS-$GOARCH
      - apk add --no-cache git gcc musl-dev tar
      - cd cli && mkdir -p $outputpath
#      - go mod tidy
      - go build -v -o $outputpath/BilibiliDanmuRobot -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r ../etc $outputpath
      - cp ../readme.md $outputpath
      - cd $outputpath
      - md5sum BilibiliDanmuRobot
      - tar czvf ../BilibiliDanmuRobot_Linux_x86_64_${DRONE_TAG}.tar.gz ./*
      - cd ../../
      - rm -rf $outputpath
    when:
      event:
        - tag
    depends_on:
      - prebuild
  - name: build-darwin-amd64
    image: golang:1.21.4-alpine
    volumes:
      - name: cache
        path: /gobuild
    environment:
      GOOS: darwin
      GOARCH: amd64
      GOCACHE: /gobuild/gocache
      GOPATH: /gobuild/gopath
    commands:
      - export outputpath=./dist/$GOOS-$GOARCH
      - apk add --no-cache git gcc musl-dev tar
      - cd cli && mkdir -p $outputpath
#      - go mod tidy
      - go build -v -o $outputpath/BilibiliDanmuRobot -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r ../etc $outputpath
      - cp ../readme.md $outputpath
      - cd $outputpath
      - md5sum BilibiliDanmuRobot
      - tar czvf ../BilibiliDanmuRobot_Darwin_x86_64_${DRONE_TAG}.tar.gz ./*
      - cd ../../
      - rm -rf $outputpath
    when:
      event:
        - tag
    depends_on:
      - prebuild
  - name: build-darwin-arm64
    image: golang:1.21.4-alpine
    volumes:
      - name: cache
        path: /gobuild
    environment:
      GOOS: darwin
      GOARCH: arm64
      GOCACHE: /gobuild/gocache
      GOPATH: /gobuild/gopath
    commands:
      - export outputpath=./dist/$GOOS-$GOARCH
      - apk add --no-cache git gcc musl-dev tar
      - cd cli && mkdir -p $outputpath
#      - go mod tidy
      - go build -v -o $outputpath/BilibiliDanmuRobot -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r ../etc $outputpath
      - cp ../readme.md $outputpath
      - cd $outputpath
      - md5sum BilibiliDanmuRobot
      - tar czvf ../BilibiliDanmuRobot_Darwin_arm64_${DRONE_TAG}.tar.gz ./*
      - cd ../../
      - rm -rf $outputpath
    when:
      event:
        - tag
    depends_on:
      - prebuild
  - name: build-windows-arm64
    image: golang:1.21.4-alpine
    volumes:
      - name: cache
        path: /gobuild
    environment:
      GOOS: windows
      GOARCH: arm64
      GOCACHE: /gobuild/gocache
      GOPATH: /gobuild/gopath
    commands:
      - export outputpath=./dist/$GOOS-$GOARCH
      - apk add --no-cache git gcc musl-dev zip
      - cd cli && mkdir -p $outputpath
#      - go mod tidy
      - go build -v -o $outputpath/BilibiliDanmuRobot.exe -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r ../etc $outputpath
      - cp ../readme.md $outputpath
      - cd $outputpath
      - md5sum BilibiliDanmuRobot.exe
      - zip -r  ../BilibiliDanmuRobot_Windows_arm64_${DRONE_TAG}.zip ./*
      - cd ../../
      - rm -rf $outputpath
    when:
      event:
        - tag
    depends_on:
      - prebuild
  - name: build-windows-amd64
    image: golang:1.21.4-alpine
    volumes:
      - name: cache
        path: /gobuild
    environment:
      GOOS: windows
      GOARCH: amd64
      GOCACHE: /gobuild/gocache
      GOPATH: /gobuild/gopath
    commands:
      - export outputpath=./dist/$GOOS-$GOARCH
      - apk add --no-cache git gcc musl-dev zip
      - cd cli && mkdir -p $outputpath
#      - go mod tidy
      - go build -v -o $outputpath/BilibiliDanmuRobot.exe -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r ../etc $outputpath
      - cp ../readme.md $outputpath
      - cd $outputpath
      - md5sum BilibiliDanmuRobot.exe
      - zip -r ../BilibiliDanmuRobot_Windows_x86_64_${DRONE_TAG}.zip ./*
      - cd ../../
      - rm -rf $outputpath
    when:
      event:
        - tag
    depends_on:
      - prebuild
  - name: github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files: cli/dist/*
    depends_on:
      - build-darwin-arm64
      - build-darwin-amd64
      - build-linux-arm64
      - build-linux-amd64
      - build-windows-amd64
      - build-windows-arm64
    when:
      event:
        - tag
volumes:
  - name: cache
    claim:
      name: robotbuild-cache
      read_only: false # <true|false>
node_selector:
  kubernetes.io/arch: "arm64"