kind: pipeline
type: kubernetes
name: default
steps:
  - name: build-linux-arm64
    image: golang:1.20.2-alpine
    environment:
      GOOS: linux
      GOARCH: arm64
    commands:
      - export outputpath=./dist/$GOOS-$GOARCH
      - apk add --no-cache git gcc musl-dev tar
      - mkdir -p $outputpath
      - go mod tidy
      - go build -v -o $outputpath/BilibiliDanmuRobot -ldflags "-X main.Version=${DRONE_TAG}" --trimpath
      - cp -r etc $outputpath
      - cp readme.md $outputpath
      - cd $outputpath
      - tar czvf ../BilibiliDanmuRobot_Linux_arm64_${DRONE_TAG}.tar.gz ./*
      - tar -ztvf ../BilibiliDanmuRobot_Linux_arm64_${DRONE_TAG}.tar.gz